_group = {
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPS,VMOVUPS,",
    offsets = "0,32,",
    addresses = "0x1940,0x19ba,",
    stride_status = "Success",
    stride = 64,
    memory_status = "Success",
    accessed_memory = 64,
    accessed_memory_nooverlap = 64,
    accessed_memory_overlap = 0,
    span = 64,
    head = 64,
    unroll_factor = 2,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPS,VMOVUPS,",
    offsets = "0,32,",
    addresses = "0x1928,0x1995,",
    stride_status = "Success",
    stride = 64,
    memory_status = "Success",
    accessed_memory = 64,
    accessed_memory_nooverlap = 64,
    accessed_memory_overlap = 0,
    span = 64,
    head = 64,
    unroll_factor = 2,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPS,VMOVUPS,",
    offsets = "0,32,",
    addresses = "0x192e,0x19ae,",
    stride_status = "Success",
    stride = 64,
    memory_status = "Success",
    accessed_memory = 64,
    accessed_memory_nooverlap = 64,
    accessed_memory_overlap = 0,
    span = 64,
    head = 64,
    unroll_factor = 2,
  },
}
