_group = {
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPS,VMOVUPS,",
    offsets = "0,32,",
    addresses = "0x17e6,0x1856,",
    stride_status = "Success",
    stride = 64,
    memory_status = "Success",
    accessed_memory = 64,
    accessed_memory_nooverlap = 64,
    accessed_memory_overlap = 0,
    span = 64,
    head = 64,
    unroll_factor = 2,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPS,VMOVUPS,",
    offsets = "0,32,",
    addresses = "0x17d0,0x1878,",
    stride_status = "Success",
    stride = 64,
    memory_status = "Success",
    accessed_memory = 64,
    accessed_memory_nooverlap = 64,
    accessed_memory_overlap = 0,
    span = 64,
    head = 64,
    unroll_factor = 2,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPS,VMOVUPS,",
    offsets = "0,32,",
    addresses = "0x17d6,0x1861,",
    stride_status = "Success",
    stride = 64,
    memory_status = "Success",
    accessed_memory = 64,
    accessed_memory_nooverlap = 64,
    accessed_memory_overlap = 0,
    span = 64,
    head = 64,
    unroll_factor = 2,
  },
}
